version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: bibliotheque_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bibliotheque
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_network

volumes:
  db_data:

networks:
  symfony_network:
    driver: bridge