version: "3.8"

services:
  database:
    image: mariadb:11.4
    container_name: bibliotheque_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bibliotheque
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot --silent"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  db_data:

networks:
  symfony_network:
    driver: bridge
